server:
  port: 8080
  tomcat:
    max-http-post-size: 2MB
    max-swallow-size: 2MB
  error:
    whitelabel:
      enabled: false
    include-stack-trace: always
  use-forward-headers: true

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true

ribbon: 
  Readtimeout: 9999999

eureka: 
  client:
    enabled: false
    serviceUrl: http://localhost:8761/eureka
  register-with-eureka: false
  fetch-registry: false

zuul: 
  ignoreSecurityHeaders: false
  ignored-services: '*'
  routes:
    auth-service:
      path: /auth/**
      url: http://localhost:10001/auth
      service-id: auth-service
      strip-prefix: true
      sensitive-headers: Cookie, Set-Cookie
    prject-service:
      path: /shopper/**
      url: http://localhost:10002/shopper
      service-id: shopper-service
      strip-prefix: true
      sensativeHeaders:
      
management:
  endpoints:
    web: 
      exposure:
        include: '*'