spring:  
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true

server:
  port: 10002
  tomcat:
    max-http-post-size: 2MB
    max-swallow-size: 2MB 

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
     
management:
  endpoints:
    web:
      exposure:
        include: '*'
